// FILE GENERATED BY scripts/generate-app-config.ts
// DO NOT EDIT MANUALLY. UPDATE tenant.setup.json AND RUN BUILD SCRIPT.

import { UNIVERSAL_PLANS, PLAN_IDS } from "./plans.catalog";
import { ProductConfig } from "./product.types";

/**
 * CONFIGURACIÓN DE AUTH
 * Generada desde tenant.setup.json
 */
const authConfig = {
    whitelist: ["admin@jokem.tech","entrenador@jokem.tech"],
};

/**
 * CONFIGURACIÓN DE EMAILS
 * Generada desde tenant.setup.json
 */
const emailConfig = {
    enabled: true,
    fromName: "Template Gym",
    fromEmail: "no-reply@jokem.tech",
};

/**
 * CONFIGURACIÓN DE UI (Visual, Themes, Branding)
 * Generada desde tenant.setup.json
 */
const uiConfig = {
// ... existing ui config ...
// I will just reuse the block below 
    gymName: "My Awesome Gym",
    gymTagline: "Train Hard",
    logo: "/images/logo.png",
    theme: {
        primary: {
            from: "#3b82f6",
            to: "#1d4ed8",
            solid: "#3b82f6",
            hover: "#2563eb",
            active: "#1d4ed8",
            focus: "#3b82f6",
        },
        secondary: {
            from: "#ffffff",
            to: "#f0f0f0",
        },
    },
    uiMode: "dark" as "light" | "dark",
    surfaces: {
        light: {
            background: "#ffffff",
            surface: "#f9fafb",
            surfaceHover: "#f3f4f6",
            border: "#e5e7eb",
            text: "#111827",
            textMuted: "#6b7280",
        },
        dark: {
            background: "#0B0B0D",
            surface: "#111113",
            surfaceHover: "#17171A",
            border: "#26262A",
            text: "#F5F5F6",
            textMuted: "#A1A1AA",
        },
    },
    poweredByJokem: {
        enabled: true,
        text: "Powered by Jokem",
        url: "https://jokem.tech",
    },
};

/**
 * CONFIGURACIÓN DE PRODUCTO
 * Generada desde tenant.setup.json
 */
const productConfig: ProductConfig = {
    timezone: "UTC",
    currency: {
    code: "USD",
    symbol: "$",
    decimals: 2,
    format: "symbol_before"
},
    units: {
    weight: "kg",
    length: "cm"
},
    membershipPlans: UNIVERSAL_PLANS,
    enabledPlans: {
        [PLAN_IDS.DAILY]: {"enabled":true,"price":10,"notes":"Day Pass"},
        [PLAN_IDS.MONTHLY]: {"enabled":true,"price":50,"notes":"Standard Membership"},
    },
    rules: {
    warningThresholdDays: 7,
    graceDays: 0,
    allowBackdatedPayments: false,
    allowFutureStartDate: true
}
};

/**
 * EXPORT FINAL
 */
export const appConfig = {
    ...uiConfig,
    ui: uiConfig,
    product: productConfig,
    auth: authConfig,
    email: emailConfig,
    __TEMPLATE_NOT_CONFIGURED__: false 
} as const;

export type AppConfig = typeof appConfig;

export function getPrimaryGradient() {
    return `linear-gradient(to right, ${appConfig.theme.primary.from}, ${appConfig.theme.primary.to})`;
}

export const themeColors = {
    primary: {
        solid: () => appConfig.theme.primary.solid,
        hover: () => appConfig.theme.primary.hover,
        active: () => appConfig.theme.primary.active,
        focus: () => appConfig.theme.primary.focus,
    },
};
