// FILE: scripts/generate-app-config.ts
import * as fs from 'fs';
import * as path from 'path';

// Define types locally to avoid import issues in script runner logic without tsconfig paths
// These mirror the JSON structure expected
interface TenantSetup {
    tenant: {
        id: string;
        timezone: string;
    };
    branding: {
        gymName: string;
        gymTagline: string;
        logoPath: string;
        uiModeDefault: "light" | "dark";
        colors: {
            primaryFrom: string;
            primaryTo: string;
            primarySolid: string;
            primaryHover: string;
            primaryActive: string;
            primaryFocus: string;
        };
    };
    product: {
        currency: any;
        units: any;
        rules: any;
        plans: Record<string, any>;
    };
    auth: {
        whitelist: string[];
    };
    email: {
        enabled: boolean;
        fromName: string;
        fromEmail: string;
    };
}

const CONFIG_PATH = path.join(process.cwd(), 'tenant.setup.json');
const OUTPUT_PATH = path.join(process.cwd(), 'src/config/app.config.ts');

if (!fs.existsSync(CONFIG_PATH)) {
    console.error(`❌ ERRROR: Configuration file not found at ${CONFIG_PATH}`);
    console.error('   Please Copy tenant.setup.json.example to tenant.setup.json and configure it.');
    process.exit(1);
}

const setup: TenantSetup = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));

const fileContent = `// FILE GENERATED BY scripts/generate-app-config.ts
// DO NOT EDIT MANUALLY. UPDATE tenant.setup.json AND RUN BUILD SCRIPT.

import { UNIVERSAL_PLANS, PLAN_IDS } from "./plans.catalog";
import { ProductConfig } from "./product.types";

/**
 * CONFIGURACIÓN DE AUTH
 * Generada desde tenant.setup.json
 */
const authConfig = {
    whitelist: ${JSON.stringify(setup.auth?.whitelist || [])},
};

/**
 * CONFIGURACIÓN DE EMAILS
 * Generada desde tenant.setup.json
 */
const emailConfig = {
    enabled: ${setup.email?.enabled ?? false},
    fromName: "${setup.email?.fromName || 'Gym'}",
    fromEmail: "${setup.email?.fromEmail || 'no-reply@example.com'}",
};

/**
 * CONFIGURACIÓN DE UI (Visual, Themes, Branding)
 * Generada desde tenant.setup.json
 */
const uiConfig = {
// ... existing ui config ...
// I will just reuse the block below 
    gymName: "${setup.branding.gymName}",
    gymTagline: "${setup.branding.gymTagline}",
    logo: "${setup.branding.logoPath}",
    theme: {
        primary: {
            from: "${setup.branding.colors.primaryFrom}",
            to: "${setup.branding.colors.primaryTo}",
            solid: "${setup.branding.colors.primarySolid}",
            hover: "${setup.branding.colors.primaryHover}",
            active: "${setup.branding.colors.primaryActive}",
            focus: "${setup.branding.colors.primaryFocus}",
        },
        secondary: {
            from: "#ffffff",
            to: "#f0f0f0",
        },
    },
    uiMode: "${setup.branding.uiModeDefault}" as "light" | "dark",
    surfaces: {
        light: {
            background: "#ffffff",
            surface: "#f9fafb",
            surfaceHover: "#f3f4f6",
            border: "#e5e7eb",
            text: "#111827",
            textMuted: "#6b7280",
        },
        dark: {
            background: "#0B0B0D",
            surface: "#111113",
            surfaceHover: "#17171A",
            border: "#26262A",
            text: "#F5F5F6",
            textMuted: "#A1A1AA",
        },
    },
    poweredByJokem: {
        enabled: true,
        text: "Powered by Jokem",
        url: "https://jokem.tech",
    },
};

/**
 * CONFIGURACIÓN DE PRODUCTO
 * Generada desde tenant.setup.json
 */
const productConfig: ProductConfig = {
    timezone: "${setup.tenant.timezone}",
    currency: ${JSON.stringify(setup.product.currency, null, 4).replace(/"([^"]+)":/g, '$1:')},
    units: ${JSON.stringify(setup.product.units, null, 4).replace(/"([^"]+)":/g, '$1:')},
    membershipPlans: UNIVERSAL_PLANS,
    enabledPlans: {
${Object.entries(setup.product.plans).map(([key, val]) => {
    // Map PLAN_ID string to computed key [PLAN_IDS.XYZ] if possible, or string literal
    const isKnownId = ["DAILY", "WEEKLY", "BIWEEKLY", "MONTHLY", "QUARTERLY", "SEMIANNUAL", "ANNUAL", "DUO", "COUPLE", "YOUTH", "SENIOR", "STUDENT", "CORPORATE", "FAMILY", "DAY_PASS_10", "DAY_PASS_20", "SESSION_8", "SESSION_12", "FREE_TRIAL", "OFF_PEAK"].includes(key);
    const keyStr = isKnownId ? `[PLAN_IDS.${key}]` : `"${key}"`;
    return `        ${keyStr}: ${JSON.stringify(val)},`;
}).join('\n')}
    },
    rules: ${JSON.stringify(setup.product.rules, null, 4).replace(/"([^"]+)":/g, '$1:')}
};

/**
 * EXPORT FINAL
 */
export const appConfig = {
    ...uiConfig,
    ui: uiConfig,
    product: productConfig,
    auth: authConfig,
    email: emailConfig,
    __TEMPLATE_NOT_CONFIGURED__: false 
} as const;

export type AppConfig = typeof appConfig;

export function getPrimaryGradient() {
    return \`linear-gradient(to right, \${appConfig.theme.primary.from}, \${appConfig.theme.primary.to})\`;
}

export const themeColors = {
    primary: {
        solid: () => appConfig.theme.primary.solid,
        hover: () => appConfig.theme.primary.hover,
        active: () => appConfig.theme.primary.active,
        focus: () => appConfig.theme.primary.focus,
    },
};
`;

fs.writeFileSync(OUTPUT_PATH, fileContent);
console.log(`✅ App config generated at: ${OUTPUT_PATH}`);
