import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { appConfig } from "@/config/app.config";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // GUARDRAIL: Prevent running unconfigured template connected to real/default DBs
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  if ((appConfig as any).__TEMPLATE_NOT_CONFIGURED__) {
    return (
      <html lang="en">
        <body>
          <div className="flex flex-col items-center justify-center min-h-screen bg-red-50 text-red-900 p-10 font-sans">
            <h1 className="text-3xl font-bold mb-4">⚠️ Template Not Configured</h1>
            <p className="text-lg mb-6">This application is running in <strong>Template Mode</strong>.</p>
            <div className="bg-white p-6 rounded shadow-md border border-red-200">
              <p className="mb-2 font-semibold">To configure this instance:</p>
              <ol className="list-decimal list-inside space-y-2 font-mono text-sm">
                <li>cp tenant.setup.json.example tenant.setup.json</li>
                <li>Edit tenant.setup.json with your details</li>
                <li>npm run tenant:build</li>
              </ol>
            </div>
          </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
